// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voices.proto

#include "ProtoDisableWarning.h"

#include "voices.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace ai {
namespace inworld {
namespace voices {
class VoiceDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Voice> _instance;
} _Voice_default_instance_;
}  // namespace voices
}  // namespace inworld
}  // namespace ai
static void InitDefaultsscc_info_Voice_voices_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ai::inworld::voices::_Voice_default_instance_;
    new (ptr) ::ai::inworld::voices::Voice();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Voice_voices_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Voice_voices_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_voices_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_voices_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_voices_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_voices_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, basename_),
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, tts_type_),
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, gender_),
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, pitch_),
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, speaking_rate_),
  PROTOBUF_FIELD_OFFSET(::ai::inworld::voices::Voice, robotic_voice_filter_level_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ai::inworld::voices::Voice)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ai::inworld::voices::_Voice_default_instance_),
};

const char descriptor_table_protodef_voices_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014voices.proto\022\021ai.inworld.voices\"\274\001\n\005Vo"
  "ice\022\020\n\010baseName\030\001 \001(\t\022,\n\010tts_type\030\002 \001(\0162"
  "\032.ai.inworld.voices.TTSType\022)\n\006gender\030\003 "
  "\001(\0162\031.ai.inworld.voices.Gender\022\r\n\005pitch\030"
  "\004 \001(\001\022\025\n\rspeaking_rate\030\005 \001(\001\022\"\n\032robotic_"
  "voice_filter_level\030\006 \001(\001*p\n\006Gender\022\034\n\030VO"
  "ICE_GENDER_UNSPECIFIED\020\000\022\025\n\021VOICE_GENDER"
  "_MALE\020\001\022\027\n\023VOICE_GENDER_FEMALE\020\002\022\030\n\024VOIC"
  "E_GENDER_NEUTRAL\020\003*7\n\007TTSType\022\025\n\021TTS_TYP"
  "E_STANDARD\020\000\022\025\n\021TTS_TYPE_ADVANCED\020\001Br\n\021a"
  "i.inworld.voicesB\016VoicesProtocolZMgithub"
  ".com/inworld-ai/inworld/serving/grpc-gat"
  "eway/build/proto/engine/v1alphab\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_voices_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_voices_2eproto_sccs[1] = {
  &scc_info_Voice_voices_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_voices_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_voices_2eproto = {
  false, false, descriptor_table_protodef_voices_2eproto, "voices.proto", 519,
  &descriptor_table_voices_2eproto_once, descriptor_table_voices_2eproto_sccs, descriptor_table_voices_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_voices_2eproto::offsets,
  file_level_metadata_voices_2eproto, 1, file_level_enum_descriptors_voices_2eproto, file_level_service_descriptors_voices_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_voices_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_voices_2eproto)), true);
namespace ai {
namespace inworld {
namespace voices {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Gender_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_voices_2eproto);
  return file_level_enum_descriptors_voices_2eproto[0];
}
bool Gender_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TTSType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_voices_2eproto);
  return file_level_enum_descriptors_voices_2eproto[1];
}
bool TTSType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Voice::_Internal {
 public:
};

Voice::Voice(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ai.inworld.voices.Voice)
}
Voice::Voice(const Voice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  basename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_basename().empty()) {
    basename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_basename(), 
      GetArena());
  }
  ::memcpy(&tts_type_, &from.tts_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&robotic_voice_filter_level_) -
    reinterpret_cast<char*>(&tts_type_)) + sizeof(robotic_voice_filter_level_));
  // @@protoc_insertion_point(copy_constructor:ai.inworld.voices.Voice)
}

void Voice::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Voice_voices_2eproto.base);
  basename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&tts_type_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&robotic_voice_filter_level_) -
      reinterpret_cast<char*>(&tts_type_)) + sizeof(robotic_voice_filter_level_));
}

Voice::~Voice() {
  // @@protoc_insertion_point(destructor:ai.inworld.voices.Voice)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Voice::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  basename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Voice::ArenaDtor(void* object) {
  Voice* _this = reinterpret_cast< Voice* >(object);
  (void)_this;
}
void Voice::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Voice::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Voice& Voice::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Voice_voices_2eproto.base);
  return *internal_default_instance();
}


void Voice::Clear() {
// @@protoc_insertion_point(message_clear_start:ai.inworld.voices.Voice)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  basename_.ClearToEmpty();
  ::memset(&tts_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&robotic_voice_filter_level_) -
      reinterpret_cast<char*>(&tts_type_)) + sizeof(robotic_voice_filter_level_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Voice::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string baseName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_basename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ai.inworld.voices.Voice.baseName"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .ai.inworld.voices.TTSType tts_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_tts_type(static_cast<::ai::inworld::voices::TTSType>(val));
        } else goto handle_unusual;
        continue;
      // .ai.inworld.voices.Gender gender = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_gender(static_cast<::ai::inworld::voices::Gender>(val));
        } else goto handle_unusual;
        continue;
      // double pitch = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double speaking_rate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          speaking_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double robotic_voice_filter_level = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          robotic_voice_filter_level_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Voice::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ai.inworld.voices.Voice)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string baseName = 1;
  if (this->basename().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_basename().data(), static_cast<int>(this->_internal_basename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ai.inworld.voices.Voice.baseName");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_basename(), target);
  }

  // .ai.inworld.voices.TTSType tts_type = 2;
  if (this->tts_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_tts_type(), target);
  }

  // .ai.inworld.voices.Gender gender = 3;
  if (this->gender() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_gender(), target);
  }

  // double pitch = 4;
  if (!(this->pitch() <= 0 && this->pitch() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_pitch(), target);
  }

  // double speaking_rate = 5;
  if (!(this->speaking_rate() <= 0 && this->speaking_rate() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_speaking_rate(), target);
  }

  // double robotic_voice_filter_level = 6;
  if (!(this->robotic_voice_filter_level() <= 0 && this->robotic_voice_filter_level() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_robotic_voice_filter_level(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ai.inworld.voices.Voice)
  return target;
}

size_t Voice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ai.inworld.voices.Voice)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string baseName = 1;
  if (this->basename().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_basename());
  }

  // .ai.inworld.voices.TTSType tts_type = 2;
  if (this->tts_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_tts_type());
  }

  // .ai.inworld.voices.Gender gender = 3;
  if (this->gender() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_gender());
  }

  // double pitch = 4;
  if (!(this->pitch() <= 0 && this->pitch() >= 0)) {
    total_size += 1 + 8;
  }

  // double speaking_rate = 5;
  if (!(this->speaking_rate() <= 0 && this->speaking_rate() >= 0)) {
    total_size += 1 + 8;
  }

  // double robotic_voice_filter_level = 6;
  if (!(this->robotic_voice_filter_level() <= 0 && this->robotic_voice_filter_level() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Voice::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ai.inworld.voices.Voice)
  GOOGLE_DCHECK_NE(&from, this);
  const Voice* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Voice>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ai.inworld.voices.Voice)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ai.inworld.voices.Voice)
    MergeFrom(*source);
  }
}

void Voice::MergeFrom(const Voice& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ai.inworld.voices.Voice)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.basename().size() > 0) {
    _internal_set_basename(from._internal_basename());
  }
  if (from.tts_type() != 0) {
    _internal_set_tts_type(from._internal_tts_type());
  }
  if (from.gender() != 0) {
    _internal_set_gender(from._internal_gender());
  }
  if (!(from.pitch() <= 0 && from.pitch() >= 0)) {
    _internal_set_pitch(from._internal_pitch());
  }
  if (!(from.speaking_rate() <= 0 && from.speaking_rate() >= 0)) {
    _internal_set_speaking_rate(from._internal_speaking_rate());
  }
  if (!(from.robotic_voice_filter_level() <= 0 && from.robotic_voice_filter_level() >= 0)) {
    _internal_set_robotic_voice_filter_level(from._internal_robotic_voice_filter_level());
  }
}

void Voice::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ai.inworld.voices.Voice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Voice::CopyFrom(const Voice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ai.inworld.voices.Voice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Voice::IsInitialized() const {
  return true;
}

void Voice::InternalSwap(Voice* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  basename_.Swap(&other->basename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Voice, robotic_voice_filter_level_)
      + sizeof(Voice::robotic_voice_filter_level_)
      - PROTOBUF_FIELD_OFFSET(Voice, tts_type_)>(
          reinterpret_cast<char*>(&tts_type_),
          reinterpret_cast<char*>(&other->tts_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Voice::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace voices
}  // namespace inworld
}  // namespace ai
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ai::inworld::voices::Voice* Arena::CreateMaybeMessage< ::ai::inworld::voices::Voice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ai::inworld::voices::Voice >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
